---
root: true

extends:
  - eslint:recommended
  - airbnb-typescript
  - airbnb/hooks
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking

parserOptions:
  ecmaVersion: 2021
  project: './tsconfig.json'

env:
  browser: true
  node: true
  es2021: true
